name: brain_buddies
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev.
publish_to: 'none'

# Versioning for your app: major.minor.patch+build
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6

  # iOS‐style icons
  cupertino_icons: ^1.0.8

  # State management
  provider: ^6.0.5

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # Local storage
  shared_preferences: ^2.0.15

  # SQLite support
  sqflite: ^2.0.2+1
  path_provider: ^2.0.11

  # Networking
  http: ^0.13.5
  audioplayers: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_tts: ^3.8.5

flutter:
  # Enables Material icons.
  uses-material-design: true

  # Your app’s asset directories.
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/images/splash.png
    - assets/images/home_bg.png
    - assets/images/logo_brain.png
    - assets/data/english_lessons.json
    - assets/images/
    - assets/audio/
    - assets/audio/a_apple.mp3
    - assets/audio/b_ball.mp3
    - assets/audio/c_cat.mp3
    - assets/data/english_quiz.json
